### ISSUE TITLE
About Box does not format well the strings, depending on the font used

### ISSUE THREAD

**Issue by redmoon1945** [artemvlas/veretino#5]
I fixed the issue by adding a GridLayout in the UI file and removing the setFixedSize in the .cpp. I dont know yet how to create a pull request, I will study that and later push it to you for review and approval.

**Comment by artemvlas** [comment]
Can you send a screenshot (here or email)? In general, I can easily redo this window. It’s just that everything looks normal on my system, but I didn’t see how it looked on others :)

**Comment by redmoon1945** [comment]
Yes, it happens quite often in the Linux world, as we are free to use any font we like. And this is very good like this. But it requires the dev to be aware of this and make the Dialog font-size-aware. I dont think it is possible to post an image here (correct me if I am wrong), so I will sent it to you by email.
Cheers
